Product.destroy_all

products = [
  # ── Electronics ──────────────────────────────────────────────
  { name: "iPhone 15 Silicone Case", category: "Electronics", description: "Slim protective case with soft-touch silicone finish. Fits iPhone 15 perfectly with precise cutouts for all ports.", price: 299, stock: 8, tags: "phone, case, protective, slim", image_url: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&h=400&fit=crop" },
  { name: "USB-C Fast Charger 65W", category: "Electronics", description: "GaN fast charger with dual USB-C ports. Compatible with laptops, phones, and tablets. Compact travel-friendly design.", price: 890, stock: 45, tags: "charger, usb-c, fast charging, travel", image_url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&h=400&fit=crop" },
  { name: "Wireless Bluetooth Earbuds", category: "Electronics", description: "True wireless earbuds with active noise cancellation. 8-hour battery life with charging case. IPX4 water resistant.", price: 1490, stock: 23, tags: "audio, wireless, bluetooth, noise cancelling, portable", image_url: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=400&fit=crop" },
  { name: "Portable Power Bank 20000mAh", category: "Electronics", description: "High-capacity power bank with LED display. Charges 3 devices simultaneously. Airline-approved for travel.", price: 750, stock: 31, tags: "power bank, portable, charging, travel, outdoor", image_url: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop" },
  { name: "Smart Watch Fitness Tracker", category: "Electronics", description: "Track steps, heart rate, sleep, and blood oxygen. Water resistant to 50m. 7-day battery life with always-on display.", price: 2490, stock: 12, tags: "fitness, wearable, health, sport, waterproof", image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop" },
  { name: "LED Desk Lamp with Wireless Charging", category: "Electronics", description: "Adjustable LED desk lamp with built-in Qi wireless charging pad. 5 brightness levels and 3 color temperatures.", price: 1290, stock: 18, tags: "lamp, desk, wireless charging, office, study", image_url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400&h=400&fit=crop" },
  { name: "Bluetooth Speaker Waterproof", category: "Electronics", description: "Compact waterproof Bluetooth speaker with 360-degree sound. 12-hour playtime. Perfect for pool, beach, or shower.", price: 990, stock: 3, tags: "audio, bluetooth, waterproof, outdoor, portable, summer", image_url: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop" },
  { name: "Webcam 1080p HD", category: "Electronics", description: "Full HD webcam with built-in microphone and auto-focus. Plug and play USB connection. Great for video calls and streaming.", price: 690, stock: 27, tags: "webcam, video, office, remote work, streaming", image_url: "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400&h=400&fit=crop" },

  # ── Sports & Outdoors ───────────────────────────────────────
  { name: "Premium Yoga Mat 6mm", category: "Sports", description: "Non-slip natural rubber yoga mat with alignment lines. Extra thick for joint comfort. Includes carry strap.", price: 890, stock: 47, tags: "yoga, fitness, mat, exercise, wellness", image_url: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop" },
  { name: "Resistance Bands Set (5 Pack)", category: "Sports", description: "Set of 5 resistance bands with varying tension levels. Includes door anchor, handles, and ankle straps. Portable gym.", price: 450, stock: 62, tags: "fitness, exercise, strength, home gym, portable", image_url: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400&h=400&fit=crop" },
  { name: "Stainless Steel Water Bottle 750ml", category: "Sports", description: "Double-wall vacuum insulated. Keeps drinks cold 24hrs or hot 12hrs. BPA-free with leak-proof lid.", price: 390, stock: 85, tags: "hydration, outdoor, gym, eco-friendly, reusable", image_url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop" },
  { name: "Cooling Towel (2 Pack)", category: "Sports", description: "Instant cooling towel that activates when wet. UPF 50 sun protection. Perfect for workouts, running, and hot weather.", price: 199, stock: 120, tags: "cooling, outdoor, summer, gym, running, heat relief", image_url: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400&h=400&fit=crop" },
  { name: "Hiking Backpack 40L", category: "Sports", description: "Lightweight hiking backpack with rain cover. Multiple compartments, hydration bladder compatible. Breathable back panel.", price: 1690, stock: 14, tags: "hiking, outdoor, travel, camping, adventure", image_url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop" },
  { name: "Jump Rope Speed Cable", category: "Sports", description: "Adjustable speed jump rope with ball bearings. Lightweight aluminum handles. Great for cardio and crossfit training.", price: 250, stock: 73, tags: "cardio, fitness, exercise, crossfit, portable", image_url: "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=400&h=400&fit=crop" },
  { name: "Camping Hammock with Mosquito Net", category: "Sports", description: "Lightweight parachute nylon hammock with integrated mosquito net. Supports up to 200kg. Includes tree straps.", price: 790, stock: 5, tags: "camping, outdoor, hammock, travel, summer, adventure", image_url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&h=400&fit=crop" },

  # ── Kitchen & Dining ────────────────────────────────────────
  { name: "Ceramic Coffee Mug Set (4 Pack)", category: "Kitchen", description: "Set of 4 minimalist ceramic mugs in earth tones. 350ml capacity. Microwave and dishwasher safe.", price: 590, stock: 2, tags: "coffee, mug, ceramic, minimalist, gift", image_url: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400&h=400&fit=crop" },
  { name: "Pour Over Coffee Dripper", category: "Kitchen", description: "Glass pour-over coffee maker with reusable stainless steel filter. Makes 1-2 cups of clean, flavorful coffee.", price: 490, stock: 34, tags: "coffee, brewing, manual, minimalist, eco-friendly", image_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=400&fit=crop" },
  { name: "Bamboo Cutting Board Set", category: "Kitchen", description: "Set of 3 organic bamboo cutting boards in different sizes. Juice groove and easy-grip handle. Naturally antimicrobial.", price: 450, stock: 41, tags: "bamboo, eco-friendly, cooking, natural, kitchen essentials", image_url: "https://images.unsplash.com/photo-1594226801341-41427b4e5c22?w=400&h=400&fit=crop" },
  { name: "Insulated Lunch Box", category: "Kitchen", description: "Double-layer stainless steel lunch box with insulated bag. Keeps food warm for 6 hours. Leak-proof design.", price: 350, stock: 56, tags: "lunch, portable, office, school, eco-friendly, reusable", image_url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&h=400&fit=crop" },
  { name: "Japanese Chef Knife 8 inch", category: "Kitchen", description: "High-carbon stainless steel chef knife with pakkawood handle. Razor-sharp edge for precise cutting. Hand-finished blade.", price: 1890, stock: 9, tags: "knife, cooking, japanese, professional, sharp", image_url: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=400&h=400&fit=crop" },
  { name: "Silicone Cooking Utensil Set (6 Pack)", category: "Kitchen", description: "Heat-resistant silicone utensils with wooden handles. Non-stick safe. Includes spatula, ladle, tongs, whisk, spoon, and turner.", price: 690, stock: 38, tags: "cooking, utensils, silicone, non-stick, kitchen essentials", image_url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop" },
  { name: "Glass Food Storage Containers (5 Pack)", category: "Kitchen", description: "Borosilicate glass containers with snap-lock lids. Oven, microwave, freezer, and dishwasher safe. Stackable design.", price: 790, stock: 22, tags: "storage, glass, meal prep, eco-friendly, reusable, kitchen essentials", image_url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400&h=400&fit=crop" },

  # ── Home & Living ────────────────────────────────────────────
  { name: "Scented Soy Candle — Lemongrass", category: "Home", description: "Hand-poured soy wax candle with Thai lemongrass essential oil. 45-hour burn time. Clean-burning with cotton wick.", price: 290, stock: 67, tags: "candle, aromatherapy, relaxation, gift, natural, thai", image_url: "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=400&h=400&fit=crop" },
  { name: "Linen Throw Pillow Cover", category: "Home", description: "Natural linen cushion cover with hidden zipper. 45x45cm. Neutral earth tone that pairs with any decor.", price: 350, stock: 43, tags: "pillow, linen, decor, minimalist, natural", image_url: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=400&h=400&fit=crop" },
  { name: "Indoor Plant Pot — Concrete", category: "Home", description: "Handmade concrete planter with drainage hole and bamboo saucer. Minimalist design. 12cm diameter.", price: 250, stock: 29, tags: "plant, pot, concrete, minimalist, decor, handmade", image_url: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400&h=400&fit=crop" },
  { name: "Woven Rattan Storage Basket", category: "Home", description: "Handwoven rattan basket with handles. Multi-purpose for laundry, toys, or blankets. Natural finish.", price: 590, stock: 16, tags: "storage, rattan, natural, handmade, decor, thai", image_url: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=400&h=400&fit=crop" },
  { name: "Essential Oil Diffuser", category: "Home", description: "Ultrasonic aroma diffuser with LED mood lighting. 300ml tank runs up to 10 hours. Whisper-quiet operation.", price: 690, stock: 21, tags: "aromatherapy, diffuser, relaxation, wellness, home", image_url: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&h=400&fit=crop" },
  { name: "Cotton Bath Towel Set (2 Pack)", category: "Home", description: "Premium long-staple cotton bath towels. Extra absorbent and quick-drying. 70x140cm. OEKO-TEX certified.", price: 490, stock: 54, tags: "towel, bath, cotton, premium, soft", image_url: "https://images.unsplash.com/photo-1583845112203-29329902332e?w=400&h=400&fit=crop" },

  # ── Fashion & Accessories ────────────────────────────────────
  { name: "Canvas Tote Bag", category: "Fashion", description: "Heavyweight organic cotton canvas tote with inner pocket. Perfect for shopping, work, or daily carry. Minimalist design.", price: 290, stock: 91, tags: "bag, tote, eco-friendly, reusable, minimalist, everyday", image_url: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop" },
  { name: "Polarized Sunglasses — Bamboo Frame", category: "Fashion", description: "UV400 polarized sunglasses with natural bamboo arms. Lightweight and eco-friendly. Includes bamboo case.", price: 590, stock: 4, tags: "sunglasses, bamboo, eco-friendly, summer, outdoor, uv protection", image_url: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop" },
  { name: "Minimalist Leather Wallet", category: "Fashion", description: "Slim bi-fold wallet in genuine leather. 6 card slots and bill compartment. RFID blocking technology.", price: 690, stock: 33, tags: "wallet, leather, minimalist, rfid, everyday", image_url: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&h=400&fit=crop" },
  { name: "Cotton Bucket Hat", category: "Fashion", description: "Lightweight cotton bucket hat with UPF 50+ sun protection. Packable and reversible. One size fits most.", price: 350, stock: 48, tags: "hat, sun protection, summer, outdoor, casual", image_url: "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=400&h=400&fit=crop" },
  { name: "Handwoven Silk Scarf", category: "Fashion", description: "Traditional Thai silk scarf with modern geometric pattern. Hand-dyed in Chiang Mai. 180x45cm.", price: 1290, stock: 7, tags: "silk, scarf, handmade, thai, luxury, gift", image_url: "https://images.unsplash.com/photo-1601370690183-1c7796ecec61?w=400&h=400&fit=crop" },

  # ── Beauty & Health ──────────────────────────────────────────
  { name: "Coconut Oil — Cold Pressed 500ml", category: "Beauty", description: "100% organic virgin coconut oil. Cold pressed for maximum nutrients. Multi-use for cooking, skin, and hair care.", price: 290, stock: 78, tags: "coconut oil, organic, natural, skincare, cooking, thai", image_url: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=400&h=400&fit=crop" },
  { name: "Natural Bamboo Toothbrush (4 Pack)", category: "Beauty", description: "Biodegradable bamboo toothbrushes with charcoal-infused bristles. Eco-friendly alternative to plastic. BPA-free.", price: 190, stock: 102, tags: "bamboo, eco-friendly, dental, natural, sustainable", image_url: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=400&h=400&fit=crop" },
  { name: "Thai Herbal Compress Ball", category: "Beauty", description: "Traditional Thai herbal compress filled with lemongrass, turmeric, kaffir lime, and camphor. Microwave to activate.", price: 150, stock: 200, tags: "herbal, thai, massage, relaxation, traditional, wellness", image_url: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=400&h=400&fit=crop" },
  { name: "Aloe Vera Gel — Organic 250ml", category: "Beauty", description: "99% pure organic aloe vera gel. Soothes sunburn, moisturizes skin. No artificial colors or fragrances.", price: 220, stock: 64, tags: "skincare, aloe vera, organic, natural, summer, soothing", image_url: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400&h=400&fit=crop" },
  { name: "Rice Bran Face Scrub", category: "Beauty", description: "Gentle exfoliating face scrub with Thai rice bran and honey. Brightens and smooths skin. For all skin types.", price: 320, stock: 36, tags: "skincare, scrub, natural, thai, brightening", image_url: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop" },

  # ── Books & Stationery ──────────────────────────────────────
  { name: "Dot Grid Notebook A5", category: "Stationery", description: "160-page dot grid notebook with 100gsm paper. Lay-flat binding. Perfect for bullet journaling, sketching, or notes.", price: 190, stock: 88, tags: "notebook, journal, writing, bullet journal, minimalist", image_url: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&h=400&fit=crop" },
  { name: "Watercolor Paint Set (24 Colors)", category: "Stationery", description: "Professional-grade watercolor palette with 24 vibrant colors. Includes travel tin and brush. Highly pigmented.", price: 590, stock: 19, tags: "art, painting, watercolor, creative, portable, gift", image_url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop" },
  { name: "Mechanical Pencil Set 0.5mm", category: "Stationery", description: "Set of 3 precision mechanical pencils with eraser refills and lead. Metal body with knurled grip. For drafting and writing.", price: 290, stock: 42, tags: "pencil, writing, drafting, office, school, precision", image_url: "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&h=400&fit=crop" },
  { name: "Washi Tape Collection (10 Rolls)", category: "Stationery", description: "Decorative washi tape in botanical and geometric patterns. 15mm x 10m each. Easy to tear and reposition.", price: 350, stock: 55, tags: "washi tape, decorative, craft, journal, gift, creative", image_url: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&h=400&fit=crop" },

  # ── Food & Beverages ─────────────────────────────────────────
  { name: "Thai Dried Mango 200g", category: "Food", description: "Premium dehydrated mango slices from Chiang Mai. No added sugar, no preservatives. Sweet and chewy.", price: 120, stock: 150, tags: "snack, mango, dried fruit, thai, natural, healthy", image_url: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=400&h=400&fit=crop" },
  { name: "Organic Jasmine Rice 1kg", category: "Food", description: "Premium Thai Hom Mali jasmine rice. Organic certified. Fragrant long-grain rice from Ubon Ratchathani.", price: 190, stock: 95, tags: "rice, organic, thai, cooking, staple, jasmine", image_url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop" },
  { name: "Cold Brew Coffee Concentrate 500ml", category: "Food", description: "Single-origin Thai arabica cold brew concentrate. 2x strength — mix with water, milk, or ice. Low acidity.", price: 280, stock: 1, tags: "coffee, cold brew, thai, beverage, summer, refreshing", image_url: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=400&fit=crop" },
  { name: "Artisan Granola — Coconut & Cashew 300g", category: "Food", description: "Small-batch granola with toasted coconut, cashews, and Thai honey. Gluten-free. Perfect with yogurt or milk.", price: 250, stock: 37, tags: "granola, breakfast, healthy, snack, gluten-free, natural", image_url: "https://images.unsplash.com/photo-1517093157656-b9eccef91cb1?w=400&h=400&fit=crop" },
  { name: "Tom Yum Paste 250g", category: "Food", description: "Authentic Tom Yum soup paste made with fresh galangal, lemongrass, and chili. Just add water and protein. Serves 6.", price: 89, stock: 110, tags: "thai, cooking, paste, spicy, authentic, traditional", image_url: "https://images.unsplash.com/photo-1569562211093-4ed0d0758f12?w=400&h=400&fit=crop" },
  { name: "Butterfly Pea Flower Tea 50g", category: "Food", description: "Dried butterfly pea flowers for naturally blue tea. Add lemon to turn purple. Caffeine-free and rich in antioxidants.", price: 150, stock: 68, tags: "tea, herbal, thai, natural, caffeine-free, colorful, wellness", image_url: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=400&fit=crop" },

  # ── Pet Supplies ─────────────────────────────────────────────
  { name: "Natural Catnip Toy Mouse", category: "Pets", description: "Handmade felt mouse toy filled with organic catnip. Safe, non-toxic materials. Set of 3 in different colors.", price: 190, stock: 44, tags: "cat, toy, catnip, natural, handmade, pet", image_url: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=400&h=400&fit=crop" },
  { name: "Adjustable Dog Harness — Medium", category: "Pets", description: "No-pull dog harness with padded chest plate. Reflective stitching for night walks. Easy step-in design.", price: 490, stock: 26, tags: "dog, harness, walking, outdoor, safety, reflective", image_url: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop" },
  { name: "Slow Feeder Dog Bowl", category: "Pets", description: "Anti-gulp puzzle bowl that slows eating by 10x. Non-slip base. Dishwasher safe. Reduces bloating and improves digestion.", price: 290, stock: 31, tags: "dog, bowl, feeding, health, pet essentials", image_url: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop" },
]

products.each do |attrs|
  Product.create!(attrs)
end

puts "Seeded #{Product.count} products"
